# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://bwolfson97.github.io/plant_pathology/"

git_url = "https://github.com/bwolfson97/plant_pathology/tree/master/"

def custom_doc_links(name): return None
