# AUTOGENERATED! DO NOT EDIT! File to edit: nbks/04_generate_pseudo_labels.ipynb (unless otherwise specified).

__all__ = ['generate_pseudo_labels']

# Cell
from fastcore.all import *
import pandas as pd
from .utils import *

# Cell
@call_parse
def generate_pseudo_labels(
    path:   Param("Directory of prediction CSVs to average", Path)=".",
    name:   Param("File name", str)="pseudo_labels.csv",
    thresh: Param("Min probabilty for pseudo label", float)=0.95,
) -> Path:
    """Generates pseudo labels and saves in path dir."""
    avg_preds = average_preds(path)

    # Only keep preds with high enough confidence
    pseudo_labels = (avg_preds.iloc[:, 1:] >= thresh)*1.0
    mask = pseudo_labels.any(axis=1)
    pseudo_labels.insert(0, "image_id", avg_preds["image_id"])
    pseudo_labels["fold"] = -1
    pseudo_labels = pseudo_labels[mask]

    pseudo_labels.to_csv(path/name, index=False)
    return path/name