# AUTOGENERATED! DO NOT EDIT! File to edit: 02_inference.ipynb (unless otherwise specified).

__all__ = ['infer_on_test_set', 'format_submission']

# Cell
from fastai.vision.all import *

# Cell
def infer_on_test_set(learn: Learner) -> Tensor:
    path_test = Path("~/kaggle/plant-pathology/data/plant-pathology-2020/test.csv")
    df_test = pd.read_csv(path_test)
    test_dl = learn.dls.test_dl(df_test)
    preds, _ = learn.get_preds(dl=test_dl)
    return preds

# Cell
def format_submission(preds: Tensor, name: str="submission.csv"):
    path = Path("/home/jupyter/kaggle/plant-pathology/data/plant-pathology-2020/")
    submission = pd.read_csv(path/"sample_submission.csv")

    # Update cols with preds
    submission["healthy"] = preds[:, 0]
    submission["multiple_diseases"] = preds[:, 1]
    submission["rust"] = preds[:, 2]
    submission["scab"] = preds[:, 3]

    save_path = path/name
    submission.to_csv(save_path, index=False)
    return save_path