# AUTOGENERATED! DO NOT EDIT! File to edit: nbks/07_pretrained_models.ipynb (unless otherwise specified).

__all__ = ['models', 'get_model']

# Cell
from torch.utils.model_zoo import load_url

# Cell
models = {}

# Cell
def get_model(model_name: str):
    """Downloads and builds pretrained model."""
    pass